<?xml-model
href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"
?>
<package format="3">
<name>handy_description</name>
<version>1.0.0</version>
<description>URDF Description package for handy robot arm</description>
<maintainer email="rishik@email.com">rishik</maintainer>
<license>BSD</license>
<buildtool_depend>ament_cmake</buildtool_depend>
<depend>robot_state_publisher</depend>
<depend>joint_state_publisher_gui</depend>
<depend>rviz2</depend>
<depend>xacro</depend>
<depend>urdf</depend>
<depend>ros_gz_sim</depend>
<depend>ros_gz_bridge</depend>
<depend>ros_gz_image</depend>
<export>
<build_type>ament_cmake</build_type>
</export>
</package>